conf:
  should_compile: true
  dtype: bfloat16
  device: cuda
  batch_size: 64
  num_workers: 2
  lr: 0.0002
  validation_probe_lr: 5e-4
  validation_probe_batch_size: 1024
  interp_warmup_steps: 100000
  train_dataset_pattern: /nvme/imagenet1k/imagenet1k-train-{0000..1023}.tar
  val_dataset_pattern: /nvme/imagenet1k/imagenet1k-validation-{00..63}.tar
  model:
    encoder:
      input_size: 768
      sliding_window_size: 5
      num_transformer_blocks: 4
      block_config:
        mlp_config:
          embed_dim: 64
          num_experts: 4
          capacity: 1.0
        attention_config:
          embed_dim: 64
          head_dim: 64
          num_attention_heads: 1
    predictor:
      input_size: 64
      num_transformer_blocks: 2
      block_config:
        mlp_config:
          embed_dim: 64
          num_experts: 4
          capacity: 1.0
        attention_config:
          embed_dim: 64
          head_dim: 64
          num_attention_heads: 1
    predictor_batch_repeat: 4
  mode: train
