conf:
  should_compile: true
  dtype: bfloat16
  device: cuda
  batch_size: 256
  num_workers: 4
  lr: 5e-4
  interp_warmup_steps: 100000
  train_dataset_pattern: /nvme/imagenet1k-256/imagenet1k-train-{0000..1023}.tar
  val_dataset_pattern: /nvme/imagenet1k-256/imagenet1k-validation-{00..63}.tar
  model:
    encoder:
      input_size: 768
      num_transformer_blocks: 8
      block_config:
        mlp_config:
          embed_dim: 128
          num_experts: 4
        attention_config:
          embed_dim: 128
          head_dim: 64
          num_attention_heads: 2
    predictor:
      input_size: 128
      num_transformer_blocks: 2
      block_config:
        mlp_config:
          embed_dim: 128
          num_experts: 4
        attention_config:
          embed_dim: 128
          head_dim: 64
          num_attention_heads: 2
    predictor_batch_repeat: 4
  mode: train
