conf:
  mode: train

  should_compile: true
  dtype: bfloat16
  device: cuda

  batch_size: 256
  num_workers: 4

  ema_beta_start: 0.996
  ema_beta: 0.9999
  ema_beta_warmup_steps: 150000

  start_lr: 1e-4
  lr: 1e-3
  num_warmup_steps: 30000

  interp_warmup_steps: 30000

  train_dataset_pattern: /nvme/imagenet1k-256/imagenet1k-train-{0000..1023}.tar
  val_dataset_pattern: /nvme/imagenet1k-256/imagenet1k-validation-{00..63}.tar

  num_register_tokens: 0
  validate_every_num_epochs: 40

  model:

    encoder:
      input_size: 768
      num_transformer_blocks: 12
      block_config:
        mlp_config:
          embed_dim: 384
          num_experts: 8
          norm_mode: dyntanh
        attention_config:
          embed_dim: 384
          head_dim: 64
          num_attention_heads: 6
          should_use_qk_norm: false
        norm_mode: dyntanh
      norm_out_mode: dyntanh
      norm_elementwise_affine: false

    predictor:
      input_size: 384
      num_transformer_blocks: 6
      block_config:
        mlp_config:
          embed_dim: 256
          num_experts: 8
          norm_mode: dyntanh
        attention_config:
          embed_dim: 256
          head_dim: 64
          num_attention_heads: 4
          should_use_qk_norm: false
        norm_mode: dyntanh
      norm_out_mode: dyntanh

    predictor_batch_repeat: 4
    target_norm_mode: disabled
    should_predict_from_all_target: false
    should_attempt_mask_dropping: true
    predictor_context_capacity: 0.25
    predictor_target_capacity: 0.25

  context_target_dataset:
    min_context_capacity: 0.25
    max_context_capacity: 0.5
    absolute_max_context_capacity: 0.5
