conf:
  should_compile: true
  dtype: bfloat16
  device: cuda
  batch_size: 256
  num_workers: 8
  ema_beta_start: 0.85
  ema_beta: 0.996
  ema_beta_warmup_steps: 500
  start_lr: 1e-4
  lr: 5e-4
  interp_warmup_steps: 30000
  train_dataset_pattern: /nvme/imagenet1k-256/imagenet1k-train-{0000..1023}.tar
  val_dataset_pattern: /nvme/imagenet1k-256/imagenet1k-validation-{00..63}.tar
  model:
    encoder:
      input_size: 768
      num_transformer_blocks: 12
      block_config:
        mlp_config:
          embed_dim: 384
          num_experts: 8
        attention_config:
          embed_dim: 384
          head_dim: 64
          num_attention_heads: 6
      norm_out_mode: disabled
    predictor:
      input_size: 384
      num_transformer_blocks: 6
      block_config:
        mlp_config:
          embed_dim: 256
          num_experts: 8
        attention_config:
          embed_dim: 256
          head_dim: 64
          num_attention_heads: 6
    predictor_batch_repeat: 4
    depthsmart_mode: disabled
    target_norm_mode: batchnorm
    should_predict_from_all_target: false
    should_attempt_mask_dropping: true
    predictor_context_capacity: 0.5
    predictor_target_capacity: 0.25
  mode: train
  validate_every_num_epochs: 10
  min_context_capacity: 0.25
  max_context_capacity: 0.95
  absolute_max_context_capacity: 0.25
