conf:
  mode: train

  should_compile: true
  dtype: bfloat16
  device: cuda

  num_epochs: 400

  ema_beta_start: 0.95
  ema_beta_warmup_steps: 1000
  ema_beta_steady: 0.999
  ema_beta_steady_steps: 300000
  ema_beta_end: 0.9995

  steady_lr: 5e-4
  num_lr_steady_steps: 9999999999

  batch_size: 256
  num_workers: 4

  num_register_tokens: 0
  validate_every_num_epochs: 100

  model:

    encoder:
      max_num_register_tokens: 0
      input_size: 768
      num_transformer_blocks: 12
      block_config:
        embed_dim: 384
        attention_config:
          embed_dim: 384
          head_dim: 64
          num_attention_heads: 6
          should_use_qk_norm: true
        norm_mode: dyntanh
        mlp_mode: diffmoe
        diffmoe_num_experts: 16
      norm_out_mode: dyntanh
      norm_elementwise_affine: false

    predictor:
      max_num_register_tokens: 0
      input_size: 384
      num_transformer_blocks: 6
      block_config:
        embed_dim: 256
        attention_config:
          embed_dim: 256
          head_dim: 64
          num_attention_heads: 4
          should_use_qk_norm: true
        norm_mode: dyntanh
        mlp_mode: diffmoe
        diffmoe_num_experts: 16
      norm_out_mode: layernorm

    predictor_batch_repeat: 4
    target_norm_mode: disabled
    should_predict_from_all_target: false
    should_attempt_mask_dropping: true
    predictor_context_capacity: 0.25
    predictor_target_capacity: 0.25

    sample_predictor_context_with_replacement: true
    sample_predictor_targets_with_replacement: true

  context_target_dataset:
    num_register_tokens: 0
    min_context_capacity: 0.25
    max_context_capacity: 0.5
    absolute_max_context_capacity: 0.5
    mask_window_size: 2
    max_side_length: 256
    min_side_length: 64

